repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
        types: [ python ]
      - id: end-of-file-fixer
        types: [ python ]
      - id: check-added-large-files
        types: [ python ]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        types: [ python ]
        args: [ --line-length=100 ]
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        types: [ python ]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
      - id: isort
        types: [ python ]
        args: ["--profile", "black"]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        args: [--skip, "B101,B104,B608,B311,B110", --recursive]  # ignore assert, binding to 0.0.0.0, hardcoded SQL, random package
  - repo: https://gitlab.com/smop/pre-commit-hooks
    rev: v1.0.0
    hooks:
      - id: check-poetry
